### ISSUE TITLE
Updating alias sometimes doesn't update it when you use /users 

### ISSUE THREAD

**Issue by caitlinosbahr** [odinecse/tunetab#2]
<img width="392" alt="screen shot 2015-12-11 at 9 52 31 pm" src="https://cloud.githubusercontent.com/assets/11053455/11759778/9624ee0a-a051-11e5-908b-0d722beab8a2.png">
In this example alex updated his alias to alex, and it appears that way in chat, but when you check /users it's still the autogenerated nickname. Weird

**Comment by odinecse** [comment]
keep em coming, fixed
